### PR TITLE
Added some documentation (also synced comments with s2disasm)

### PR DESCRIPTION
**Pull request by GabrielRavier**

### CODE REVIEW

**Comment by fredbronze** [comment]
I'm not sure I appreciate the move towards s2disasm's terser "NemDec" and friends -- this isn't 1992, we don't have to keep names under eight characters.

**Comment by GabrielRavier** [comment]
I think I'll move it back after fixing the build (i literally only forgot to check after the last commit)

**Comment by GabrielRavier** [comment]
I moved it back so you can either merge the pr or tell me more things i did wrong

**Comment by fredbronze** [comment]
Those aren't the original labels. You just changed them to a third thing which doesn't match the S2 disassembly OR how it used to be in the S3K disassembly.

I suggest you take a step back and pay a bit more mind to what you're doing. There are definitely some good ideas here, but at the moment they're buried in a mountain of haste and false starts.

**Comment by GabrielRavier** [comment]
I've moved the names back (and added majuscules on some for consistency). Also, if you want to pinpoint more precisely where I may have made mistakes and such, note that you can [add line comments to a pull request](https://help.github.com/articles/commenting-on-a-pull-request/#adding-line-comments-to-a-pull-request)

**Comment by GabrielRavier** [comment]
Gonna go make a new PR instead of the current garbage state of this thing.

**Comment by GabrielRavier** [comment]
(PS: I'm not planning on making a new PR for this, after further consideration the changes are frankly just too hard to salvage and they aren't necessarily relevant anymore anyway - if anybody else wants to do it then I guess go for it, but it seems like a lost cause for me given it's based on stuff from 4 years ago and I'm not really interested in working on this project at the moment)

**Pull request closed without merging**
